export const products = [
  {
    id: 1,
    title: "스타벅스 아메리카노 T",
    price: 3.8,
    image: [
      "/images/sample/starbucks.jpg",
      "/images/sample/cu.jpg",
      "/images/sample/baskin.jpg",
    ],
    seller: "김지민",
    creditScore: "93",
    timeAgo: "3일 전",
    category: "카페",
  },
  {
    id: 2,
    title: "스타벅스 아메리카노 T",
    price: 3.9,
    image: [
      "/images/sample/starbucks.jpg",
      "/images/sample/mcdonalds.jpg",
      "/images/sample/baskin.jpg",
    ],
    seller: "박서준",
    creditScore: "88",
    timeAgo: "3일 전",
    category: "카페",
  },
  {
    id: 3,
    title: "CU 모바일상품권 2,000원",
    price: 1.7,
    image: [
      "/images/sample/cu.jpg",
      "/images/sample/starbucks.jpg",
      "/images/sample/mcdonalds.jpg",
    ],
    seller: "이하늘",
    creditScore: "97",
    timeAgo: "30분 전",
    category: "상품권",
  },
  {
    id: 4,
    title: "베스킨라빈스 파인트 아이스크림",
    price: 5.8,
    image: [
      "/images/sample/baskin.jpg",
      "/images/sample/starbucks.jpg",
      "/images/sample/cu.jpg",
    ],
    seller: "최유진",
    creditScore: "82",
    timeAgo: "1일 전",
    category: "식품",
  },
  {
    id: 5,
    title: "맥도날드 빅맥 세트",
    price: 6.1,
    image: [
      "/images/sample/mcdonalds.jpg",
      "/images/sample/baskin.jpg",
      "/images/sample/starbucks.jpg",
    ],
    seller: "정민석",
    creditScore: "95",
    timeAgo: "1초 전",
    category: "식품",
  },
];
